### ISSUE TITLE
FileNotFoundError on Windows

### ISSUE THREAD

**Issue by gianpaolo-lopresti** [ErDmKo/asyncmc#10]
Hi,
on asyncmc 0.6.6 the pip install gives the following error on Windows 10:

FileNotFoundError: [Errno 2] No such file or directory: 'user temp dir\\asyncmc\\CHANGES.md'

The same error does not happen with the 0.6.5 version.

Regards.

**Comment by ErDmKo** [comment]
Thanks for feedback i will fix it ASAP

**Comment by gianpaolo-lopresti** [comment]
Thanks to you for this great library!

**Comment by ErDmKo** [comment]
Fixed in 0.6.7
